---
title: 'Reproducible Research: Peer Assignment 1'
author: "Kirsten Cook"
date: "2024-07-10"
output:
  html_document: default
  pdf_document: default
---

##Loading and preprocessing the data
```{r, echo = TRUE}
library(ggplot2)
setwd("C:/Users/Loaner - Kirsten/Desktop/Coursera")
unzip("repdata_data_activity.zip")
initialData <- data.table::fread(input = "activity.csv")
```
##What is mean total number of steps taken per day?
```{r, echo=TRUE}
stepsPerDay <- initialData[, c(lapply(.SD, sum, na.rm=FALSE)), .SDcols = c("steps"), by = .(date)]
head(stepsPerDay, 10)
ggplot(stepsPerDay, aes(x=steps)) +
  geom_histogram(fill="blue", binwidth = 1000) +
  labs(title = "Steps Each Day", x= "Steps", y = "Frequency")
stepsPerDay[, .(Mean_Steps = mean(steps, na.rm = TRUE), Median_Steps = median(steps, na.rm = TRUE))]
```
##What is the average daily activity pattern?
```{r, echo=TRUE}
stepsPerInterval <- initialData[, c(lapply(.SD, mean, na.rm=TRUE)), .SDcols = c("steps"), by = .(interval)]
ggplot(stepsPerInterval, aes(x=interval, y=steps)) + geom_line(color="blue", linewidth=1) + labs(title="Average Daily Steps", x= "Interval", y= "Average Steps Per Day")
stepsPerInterval[steps == max(steps), .(max_interval = interval)]
```
##Imputing Missing Values
```{r,echo=TRUE}
initialData[is.na(steps), .N ]

```
```{r,echo=TRUE}
initialData[is.na(steps), "steps"] <- initialData[, c(lapply(.SD, median, na.rm = TRUE)), .SDcols = c("steps")]
data.table::fwrite(x = initialData, file = "activity.csv", quote = FALSE)
Total_Steps <- initialData[, c(lapply(.SD, sum)), .SDcols = c("steps"), by = .(date)] 
Total_Steps[, .(Mean_Steps = mean(steps), Median_Steps = median(steps))]
ggplot(Total_Steps, aes(x = steps)) + geom_histogram(fill = "blue", binwidth = 1000) + labs(title = "Daily Steps", x = "Steps", y = "Frequency")
```

##Are there differences in activity patterns between weekdays and weekends?
```{r,echo=TRUE}
initialData$date <- as.Date(strptime(initialData$date, format= "%Y-%m-%d"))
initialData$dayType <- sapply(initialData$date, function(x) {
  if(weekdays(x) == "Saturday" | weekdays(x) == "Sunday")
  {y <- "Weekend"}
  else {y<- "Weekday"}
  y
})
initialDataByDay <- aggregate(steps ~ interval + dayType, initialData, mean, na.rm = TRUE)
dayPlot <- ggplot(initialDataByDay, aes(x=interval, y=steps, color=dayType))+ geom_line()+ggtitle("Average Daily Steps by Day Type") + 
  xlab("Interval")+
  ylab("Average Number of Steps")+
  facet_wrap(~dayType, ncol=1, nrow=2)
print(dayPlot)
```

